(define abbr `((pl . "please")
               (ye .  "yes")
               (ag . "again")
               (di . "dial")
               (th . "thanks")
               (mni . "my name is")
               (sat . "saturday")
               (sun . "sunday")
               (mon . "monday")
               (tue . "tues")
               (wed . "wed")
               (thu . "thursday")
               (fri . "friday")
               (im  . "i'm")))
